DISC:
  clip_obs: 20
  disc_acs_select_dim: null
  disc_batch_size: null
  disc_eps: 1e-05
  disc_layers:
  - 30
  disc_learning_rate: 0.003
  disc_normalize": false
  disc_obs_select_dim: null
  disc_plot_every: 1
  freeze_gail_weights: false
  gail_path: null
  learn_cost: true
  num_spurious_features: null
  use_cost_net: false
  use_cost_shaping_callback: false
PPO:
  batch_size: 64
  clip_range: 0.2
  ent_coef: 0.0
  learning_rate: 0.0003
  max_grad_norm: 0.5
  n_epochs: 10
  n_steps: 2048
  policy_layers:
  - 64
  - 64
  policy_name: MlpPolicy
  reward_gae_lambda: 0.95
  reward_gamma: 0.99
  reward_vf_coef: 0.5
  reward_vf_layers:
  - 64
  - 64
  sde_sample_freq: -1
  shared_layers: null
  target_kl: 0.01
  timesteps: 8000000
  use_sde: false
device: cuda
env:
  config_path: null
  cost_gamma: 0.99
  cost_info_str: cost
  dont_normalize_obs: false
  dont_normalize_reward: false
  eval_env_id: HCWithPos-v0
  num_threads: 5
  record_info_input_dims:
  - 0
  record_info_names:
  - xpos
  reward_gamma: 0.99
  save_dir: ../save_model
  train_env_id: HCWithPos-v0
  use_cost: true
  visualize_info_ranges:
  - - -30
    - 30
group: GAIL
multi_env: true
running:
  eval_every: 200000
  expert_path: ../data/expert_data/HCWithPos-New/
  expert_rollouts: 10
  save_every: 500000
task: GAIL-HC
verbose: 2
